title: Vibe Coding Without Agentforce Vibes
description: Agentic Salesforce development using IntelliJ IDEA, Illuminated Cloud, and GitHub CoPilot
show_downloads: false
theme: jekyll-theme-hacker
plugins:
  - jekyll-remote-theme